// Női kihíváscsomag (100 db) beírása a KIHÍVÁSKATALÓGUS fülre.
// Használat: Sheet › Bővítmények › Apps Script › illeszd be ezt a fájlt › futtasd: noiKihivasokBeirasa
// Többször is futtatható: a Forrássor (M oszlop) alapján már bent lévő sort nem ír be újra.

const TARGET_GID = 2100000104;
const HEADER_ROW = 3;
const HEADERS = ['Kihívás', 'Leírás', 'Korábbi label', 'Időtartam', 'Típus', 'Célcsoport', 'Irány',
  'Érett célvonás', 'Korrigált torzulás', 'Dimenzió', 'Szerző', 'Aktív', 'Forrássor'];

const ROWS = [
  ["Én hívom randira", "Szervezz meg ma egy kettesben töltött estét a férjeddel a következő két hétre: te intézd a gyerekvigyázót, az időpontot és a programot is, ne várd, hogy ő kezdeményezzen.", "AI – Lelki", 1, "Napi", "Női", "Előre", "Kezdeményezés", "Impulzivitás", "Lelki", "ai_user", true, "AI-NE-01"],
  ["Új anyuka", "A héten szólíts meg egy anyukát a játszótéren, az oviban vagy a gyülekezetben, akit még alig ismersz, és kezdeményezz vele egy második találkozót is (séta, kávé, közös játszótér).", "AI – Lelki", 7, "Heti", "Női", "Előre", "Kezdeményezés", "Impulzivitás", "Lelki", "ai_user", true, "AI-NE-02"],
  ["Mozgásindító", "Ma te kezdeményezz közös mozgást a családdal: séta, biciklizés, labdázás vagy kirándulás. Legalább 45 perc legyen, a telefon pedig maradjon zsebben.", "AI – Fizikai", 1, "Napi", "Koedukált", "Előre", "Kezdeményezés", "Impulzivitás", "Fizikai", "ai_user", true, "AI-NE-03"],
  ["Ötletből terv", "Van egy ötleted a családod vagy a közösséged számára, amit régóta dédelgetsz? Írd le ma egy oldalon a célt és az első három lépést, és még ma szólj annak, akire az elsőhöz szükséged van.", "AI – Szellemi", 1, "Napi", "Koedukált", "Előre", "Kezdeményezés", "Impulzivitás", "Szellemi", "ai_user", true, "AI-NE-04"],
  ["Kimondom", "Mondd el ma a férjednek egy kérésedet vagy érzésedet, amit régóta magadban tartasz. Egyszerűen, szemrehányás nélkül: „Szükségem lenne arra, hogy…”", "AI – Szellemi", 1, "Napi", "Női", "Előre", "Bátorság", "Vakmerőség", "Szellemi", "ai_user", true, "AI-NE-05"],
  ["Egyedül is", "Vállalj el ma egy olyan fizikai feladatot, amivel eddig mindig mást vártál (bútor összeszerelése, polc felfúrása, gumi ellenőrzése, kerti munka). Biztonságosan, szükség esetén videós útmutatóval.", "AI – Fizikai", 1, "Napi", "Női", "Előre", "Bátorság", "Vakmerőség", "Fizikai", "ai_user", true, "AI-NE-06"],
  ["Hétköznapi bizonyság", "Öt napon át oszd meg naponta egy nőtársaddal (élőben, üzenetben vagy hangüzenetben), mit tett Isten érted aznap vagy az utóbbi időben.", "AI – Lelki", 5, "Heti", "Női", "Előre", "Bátorság", "Vakmerőség", "Lelki", "ai_user", true, "AI-NE-07"],
  ["Új terep", "A héten tegyél meg valamit, amitől tartasz, de tudod, hogy jó lenne: jelentkezz egy szolgálatba, vállald egy beszélgetés vezetését a kiscsoportban, vagy iratkozz be egy tanfolyamra.", "AI – Szellemi", 7, "Heti", "Női", "Előre", "Bátorság", "Vakmerőség", "Szellemi", "ai_user", true, "AI-NE-08"],
  ["Rendrakó hadjárat", "Öt napon át foglalj vissza naponta 20 perc alatt egy „elveszett” területet az otthonodban (fiók, kamra, gyerekruhás szekrény). Nem a tökéletesség a cél, hanem hogy a hét végére könnyebb legyen élni.", "AI – Fizikai", 5, "Heti", "Női", "Előre", "Hódítás", "Agresszió vagy uralkodás", "Fizikai", "ai_user", true, "AI-NE-09"],
  ["Egyszer mondom", "Ma minden kérést egyszer, nyugodt hangon és szemkontaktussal mondj el a gyerekeknek. Ha nem teljesül, cselekedj: menj oda és segíts elindulni, ismételgetés és kiabálás helyett.", "AI – Szellemi", 1, "Napi", "Női", "Előre", "Határozottság", "Erőszakosság", "Szellemi", "ai_user", true, "AI-NE-10"],
  ["Kiabálásmentes hét", "Egy héten át ne emeld fel a hangodat a gyerekeidre vagy a férjedre. Ha mégis megtörténik, kérj bocsánatot, és jegyezd fel, mi előzte meg.", "AI – Lelki", 7, "Heti", "Női", "Előre", "Határozottság", "Erőszakosság", "Lelki", "ai_user", true, "AI-NE-11"],
  ["Egymondatos nem", "Mondj ma nemet egy olyan felkérésre, amit csak megfelelési kényszerből vállalnál el: egy mondatban, kedvesen, magyarázkodás és bűntudat nélkül.", "AI – Szellemi", 1, "Napi", "Női", "Előre", "Határozottság", "Erőszakosság", "Szellemi", "ai_user", true, "AI-NE-12"],
  ["Esti rend", "Öt estén át vezesd végig következetesen a gyerekek esti rutinját egy előre kitűzött időpontra (fürdés, mese, ima, lámpaoltás), alkudozás nélkül, de szeretettel.", "AI – Fizikai", 5, "Heti", "Női", "Előre", "Határozottság", "Erőszakosság", "Fizikai", "ai_user", true, "AI-NE-13"],
  ["Saját fejlődés", "A héten tölts legalább 3 × 30 percet egy olyan készség fejlesztésével, ami a tiéd (nyelv, hangszer, szakmai tudás, kézművesség), a gyerekek alvásidejében vagy a férjeddel egyeztetett időben.", "AI – Szellemi", 7, "Heti", "Női", "Előre", "Ambíció", "Törtetés", "Szellemi", "ai_user", true, "AI-NE-14"],
  ["Álmaim listája", "Írd le, mit szeretnél még megvalósítani az életedben, az anyaságon túl is. Válassz ki egyet, és írd mellé a legkisebb első lépést, amit még idén megtehetsz.", "AI – Szellemi", 1, "Napi", "Női", "Előre", "Ambíció", "Törtetés", "Szellemi", "ai_user", true, "AI-NE-15"],
  ["Öt nap, öt zsoltár", "Öt napon át olvass el naponta egy zsoltárt vagy egy fejezetet a Példabeszédekből akkor is, ha csak 5 perced van. Mindegyikből írj ki magadnak egy mondatot.", "AI – Lelki", 5, "Heti", "Női", "Hátra", "Kitartás", "Makacsság", "Lelki", "ai_user", true, "AI-NH-01"],
  ["Végigviszem", "Válassz egy háztartási feladatot, amit rendszeresen félbehagysz (teregetés, mosogatógép kipakolása, vasalnivaló), és ma vidd végig az elejétől a végéig.", "AI – Fizikai", 1, "Napi", "Női", "Hátra", "Kitartás", "Makacsság", "Fizikai", "ai_user", true, "AI-NH-02"],
  ["Elv vagy megszokás?", "Egy mai vitában, ahol ragaszkodnál a saját megoldásodhoz, kérdezd meg magadtól: elvi kérdés ez, vagy csak megszokás? Ha megszokás, engedd a másik útját.", "AI – Szellemi", 1, "Napi", "Koedukált", "Hátra", "Kitartás", "Makacsság", "Szellemi", "ai_user", true, "AI-NH-03"],
  ["Az ő módszere", "Hagyd ma, hogy a férjed a saját módján végezzen el egy feladatot a gyerekekkel (öltöztetés, fürdetés, pakolás), javítás, utólagos rendbetétel és megjegyzés nélkül.", "AI – Lelki", 1, "Napi", "Női", "Hátra", "Védelem", "Kontrollálás", "Lelki", "ai_user", true, "AI-NH-04"],
  ["Apás délután", "Adj ki a kezedből egy délutánt: a férjed legyen a gyerekekkel, te pedig menj el otthonról. Ne hagyj részletes utasításlistát, és ne telefonálj haza ellenőrizni.", "AI – Fizikai", 1, "Napi", "Női", "Hátra", "Védelem", "Kontrollálás", "Fizikai", "ai_user", true, "AI-NH-05"],
  ["Gyerekszemmel", "Járd végig guggolva, gyerekszemmel a lakást, és szüntess meg ma három veszélyforrást: szabad konnektor, éles sarok, elérhető gyógyszer vagy tisztítószer.", "AI – Fizikai", 1, "Napi", "Koedukált", "Hátra", "Védelem", "Kontrollálás", "Fizikai", "ai_user", true, "AI-NH-06"],
  ["Aggodalmak átadása", "Írd le, mi miatt aggódsz ma a gyerekeid vagy a családod kapcsán. Mindegyik mellé írd oda, mit tehetsz te, és mit adsz át Istennek. Az átadottakért imádkozz, majd húzd át őket.", "AI – Lelki", 1, "Napi", "Női", "Hátra", "Védelem", "Kontrollálás", "Lelki", "ai_user", true, "AI-NH-07"],
  ["Képernyőőr hete", "Egy héten át tudatosan őrizd a gyerekek és a saját képernyőidődet: előre döntsd el a keretet, és tartsd be. A cél a védelem, nem a büntetés, ezért adj helyette közös alternatívát.", "AI – Szellemi", 7, "Heti", "Női", "Hátra", "Védelem", "Kontrollálás", "Szellemi", "ai_user", true, "AI-NH-08"],
  ["Ellenőrzés helyett bizalom", "Öt napon át ne ellenőrizd utólag, hogy a férjed vagy a nagyobb gyereked elvégezte-e, amit vállalt: ne kérdezz rá és ne nézd meg. Bízd rájuk, és figyeld meg, mi történik benned.", "AI – Szellemi", 5, "Heti", "Női", "Hátra", "Védelem", "Kontrollálás", "Szellemi", "ai_user", true, "AI-NH-09"],
  ["Húsz perc előny", "Öt reggelen át kelj fel 20 perccel a gyerekek előtt, hogy a nap ne rohanással induljon. Ha közben valami csúszik, mondd ki magadban: „Van időnk.”", "AI – Fizikai", 5, "Heti", "Női", "Hátra", "Türelem", "Passzivitás", "Fizikai", "ai_user", true, "AI-NH-10"],
  ["Levegővétel-szabály", "Ma minden alkalommal, amikor egy hiszti vagy egy megjegyzés felhúz, vegyél tíz lassú levegőt, mielőtt megszólalsz. Este írd fel, hányszor sikerült.", "AI – Lelki", 1, "Napi", "Női", "Hátra", "Türelem", "Passzivitás", "Lelki", "ai_user", true, "AI-NH-11"],
  ["A gyerek tempójában", "Sétálj ma a gyerekeddel úgy, hogy ő diktálja a tempót és az irányt (biztonságos keretek között). Ne siettesd, csak kísérd, és figyeld, mit fedez fel.", "AI – Fizikai", 1, "Napi", "Női", "Hátra", "Türelem", "Passzivitás", "Fizikai", "ai_user", true, "AI-NH-12"],
  ["Nem nyelem le", "Öt napon át, ha valami zavar a családban vagy a közösségben, ne nyeld le, és ne várd, hogy magától megoldódjon: még aznap fogalmazd meg nyugodtan, egy mondatban.", "AI – Szellemi", 5, "Heti", "Női", "Hátra", "Türelem", "Passzivitás", "Szellemi", "ai_user", true, "AI-NH-13"],
  ["Várakozás hete", "Van egy ügy, amiben türelmetlenül várod a változást (a férjed, egy gyerek, egy helyzet)? Egy héten át naponta imádkozz érte, és írd le, mit tehetsz addig hűségesen, sürgetés és nyomásgyakorlás nélkül.", "AI – Lelki", 7, "Heti", "Női", "Hátra", "Türelem", "Passzivitás", "Lelki", "ai_user", true, "AI-NH-14"],
  ["Érzésnapló", "Öt estén át írd le a nap három legerősebb érzését (düh, szomorúság, öröm, félelem), és hogy mi váltotta ki őket. Ne ítélkezz, csak nevezd meg őket. A hét végén vidd mindezt Isten elé.", "AI – Lelki", 5, "Heti", "Női", "Hátra", "Önuralom", "Elfojtás", "Lelki", "ai_user", true, "AI-NH-15"],
  ["Görgetésmentes hét", "Öt napon át ne görgesd a közösségi médiát (Instagram, Facebook, TikTok). A felszabaduló időben olvass, pihenj vagy beszélgess.", "AI – Szellemi", 5, "Heti", "Női", "Hátra", "Önuralom", "Elfojtás", "Szellemi", "ai_user", true, "AI-NH-16"],
  ["Az én szükségem", "Nevezz meg ma egy saját szükségletedet (alvás, csend, mozgás, beszélgetés), és kérj segítséget a férjedtől vagy mástól, hogy teljesülhessen.", "AI – Szellemi", 1, "Napi", "Női", "Hátra", "Önuralom", "Elfojtás", "Szellemi", "ai_user", true, "AI-NH-17"],
  ["Előbb Istennek", "Ha ma sírni, dühöngeni vagy panaszkodni volna kedved, előbb mondd el Istennek hangosan vagy írásban, szépítés nélkül, és csak utána beszélj róla emberekkel.", "AI – Lelki", 1, "Napi", "Női", "Hátra", "Önuralom", "Elfojtás", "Lelki", "ai_user", true, "AI-NH-18"],
  ["Időben lefekszem", "Öt estén át feküdj le legkésőbb egy előre kijelölt időpontban (például 22:30-kor) akkor is, ha lenne még mit elpakolni. Ami kimaradt, ráér holnap.", "AI – Fizikai", 5, "Heti", "Koedukált", "Hátra", "Önuralom", "Elfojtás", "Fizikai", "ai_user", true, "AI-NH-19"],
  ["Újra őt választanám", "Írj kézzel levelet a férjednek arról, miért választanád újra. Idézz fel benne egy konkrét emléket a kapcsolatotok elejéről.", "AI – Lelki", 1, "Napi", "Női", "Hátra", "Hűség", "Változásképtelenség", "Lelki", "ai_user", true, "AI-NH-20"],
  ["Imádkozom érte", "Egy héten át minden nap imádkozz a férjedért egy-egy konkrét területen (munka, hit, egészség, apaság, barátságok). A hét végén mondd el neki, miért imádkoztál.", "AI – Lelki", 7, "Heti", "Női", "Hátra", "Hűség", "Változásképtelenség", "Lelki", "ai_user", true, "AI-NH-21"],
  ["Mindig így volt?", "Keress a családotok napirendjében egy szokást, amit csak azért tartotok, mert „mindig így volt”, pedig már nem szolgál. Beszéld meg a férjeddel, és próbáljatok ki helyette valami újat.", "AI – Szellemi", 1, "Napi", "Női", "Hátra", "Hűség", "Változásképtelenség", "Szellemi", "ai_user", true, "AI-NH-22"],
  ["Ez a mai terv", "Ha ma felborul a terved (beteg gyerek, elmaradt alvás, váratlan vendég), mondd ki: „Rendben, akkor ez a mai terv”, és válassz ki egyetlen dolgot, ami ma igazán fontos.", "AI – Lelki", 1, "Napi", "Női", "Oldalra", "Rugalmasság", "Megalkuvás", "Lelki", "ai_user", true, "AI-NO-01"],
  ["Kedvesen, de szilárdan", "Egy héten át figyeld meg, hol engedsz csak azért, hogy ne legyen konfliktus (gyerek, férj, anyós, kolléga). Válassz ki egy helyzetet, ahol az elv fontos, és ott tarts ki kedvesen, de szilárdan.", "AI – Szellemi", 7, "Heti", "Női", "Oldalra", "Rugalmasság", "Megalkuvás", "Szellemi", "ai_user", true, "AI-NO-02"],
  ["Babakocsis edzés", "Öt napon át mozogj legalább 30 percet abban, ami adott: tolj tempósan babakocsit, guggolj, amíg a gyerek játszik, vagy táncolj vele. Ne a tökéletes edzésre várj.", "AI – Fizikai", 5, "Heti", "Női", "Oldalra", "Rugalmasság", "Megalkuvás", "Fizikai", "ai_user", true, "AI-NO-03"],
  ["Előbb az ő ötlete", "Öt napon át egy családi döntésnél (vacsora, program, vásárlás) kérdezd meg először a házastársad véleményét, és ha nem elvi kérdés, fogadd el az övét.", "AI – Szellemi", 5, "Heti", "Koedukált", "Oldalra", "Rugalmasság", "Megalkuvás", "Szellemi", "ai_user", true, "AI-NO-04"],
  ["Maradékmester", "Főzz ma egy ételt abból, ami éppen otthon van, külön bevásárlás nélkül. Ha kell, kérdezd meg a gyerekeket, mi legyen belőle.", "AI – Fizikai", 1, "Napi", "Koedukált", "Oldalra", "Kreativitás", "Szabálykerülés", "Fizikai", "ai_user", true, "AI-NO-05"],
  ["Dobozvár", "Találj ki a gyerekekkel egy új játékot vagy programot otthoni dolgokból (dobozvár, kincskeresés, bábszínház). Te is játssz velük, ne csak felügyelj.", "AI – Fizikai", 1, "Napi", "Női", "Oldalra", "Kreativitás", "Szabálykerülés", "Fizikai", "ai_user", true, "AI-NO-06"],
  ["Igék a hűtőn", "Öt napon át írj ki naponta egy igeverset cetlire, és tedd ki oda, ahol sokat vagy (hűtő, tükör, pelenkázó). Minden nap tanuld meg az aznapit.", "AI – Lelki", 5, "Heti", "Női", "Oldalra", "Kreativitás", "Szabálykerülés", "Lelki", "ai_user", true, "AI-NO-07"],
  ["Telefon helyett", "Figyeld meg ma, mikor nyúlsz a telefonodért menekülésként (unalom, fáradtság, feszültség). Ilyenkor válassz helyette mást: egy pohár víz, öt perc ima, egy ölelés valakinek.", "AI – Szellemi", 1, "Napi", "Koedukált", "Oldalra", "Bölcs kerülőút", "Menekülés", "Szellemi", "ai_user", true, "AI-NO-08"],
  ["Mielőtt kifogyok", "Egy héten át, amikor érzed, hogy fogy az erőd, ne húzd tovább egyedül, és ne menekülj sorozatba vagy vásárlásba: kérj segítséget (férj, nagyszülő, barátnő), és pihenj.", "AI – Lelki", 7, "Heti", "Női", "Oldalra", "Bölcs kerülőút", "Menekülés", "Lelki", "ai_user", true, "AI-NO-09"],
  ["Tizenöt perc levegő", "Ha ma feszült helyzet alakul ki otthon, ne vonulj el sértődötten és ne robbanj: jelezd, hogy 15 percre kimész, sétálj vagy állj ki az erkélyre, imádkozz, majd térj vissza, és beszéljétek meg.", "AI – Fizikai", 1, "Napi", "Női", "Oldalra", "Bölcs kerülőút", "Menekülés", "Fizikai", "ai_user", true, "AI-NO-10"],
  ["Ma elintézem", "Van egy telefonhívás vagy intéznivaló, amit hetek óta tologatsz (orvos, hivatal, óvoda, számla)? Intézd el ma délelőtt, mielőtt bármi mást elkezdenél.", "AI – Szellemi", 1, "Napi", "Koedukált", "Oldalra", "Bölcs kerülőút", "Menekülés", "Szellemi", "ai_user", true, "AI-NO-11"],
  ["Egyenes kérés", "Ma ne célozgass, ne sóhajts, és ne várd, hogy a férjed kitalálja, mit szeretnél: kérj egyenesen, egy mondatban. („Szeretném, ha ma te fürdetnéd a gyerekeket.”)", "AI – Szellemi", 1, "Napi", "Női", "Oldalra", "Diplomácia", "Manipuláció", "Szellemi", "ai_user", true, "AI-NO-12"],
  ["Anyós-híd", "A héten tegyél egy kedves, békességet építő lépést az anyósod (vagy apósod, sógornőd) felé: hívd fel, kérj tőle tanácsot valamiben, vagy köszönj meg neki valamit konkrétan.", "AI – Lelki", 7, "Heti", "Női", "Oldalra", "Diplomácia", "Manipuláció", "Lelki", "ai_user", true, "AI-NO-13"],
  ["Duzzogás helyett", "Három napon át, ha megbántódsz, ne hallgass és ne éreztesd hűvösséggel: még aznap mondd el nyugodtan, mi esett rosszul, és mire lenne szükséged.", "AI – Lelki", 3, "Heti", "Női", "Oldalra", "Diplomácia", "Manipuláció", "Lelki", "ai_user", true, "AI-NO-14"],
  ["Testvérbéke", "Ha ma összevesznek a gyerekeid, ne ítélkezz azonnal: kérdezd meg mindkettőt, mi történt, foglald össze, amit hallottál, és segíts nekik maguknak megtalálni a megoldást.", "AI – Szellemi", 1, "Napi", "Női", "Oldalra", "Diplomácia", "Manipuláció", "Szellemi", "ai_user", true, "AI-NO-15"],
  ["Pletykaszűrő", "Öt napon át, mielőtt valakiről beszélsz, aki nincs jelen, kérdezd meg magadtól: igaz, szükséges és építő? Ha nem, hallgass, vagy tereld el kedvesen a beszélgetést.", "AI – Szellemi", 5, "Heti", "Női", "Oldalra", "Diplomácia", "Manipuláció", "Szellemi", "ai_user", true, "AI-NO-16"],
  ["Kinek felelek meg?", "Írd le, kiknek akarsz folyamatosan megfelelni (szülők, anyós, más anyukák, közösség). Mindegyik mellé írd oda, mit vár ebben tőled Isten, és döntsd el, miben nem kell tovább megfelelned.", "AI – Szellemi", 1, "Napi", "Női", "Oldalra", "Alkalmazkodás", "Elvtelenség", "Szellemi", "ai_user", true, "AI-NO-17"],
  ["Az ő világa", "Szánj ma időt arra, ami a férjednek fontos (hobbi, sport, munka): kérdezz róla, hallgasd meg érdeklődéssel, vagy csináljátok együtt, még ha téged kevésbé érdekel is.", "AI – Lelki", 1, "Napi", "Női", "Oldalra", "Alkalmazkodás", "Elvtelenség", "Lelki", "ai_user", true, "AI-NO-18"],
  ["Új arc a közösségben", "A héten ülj le a gyülekezetben vagy egy közösségi alkalmon valaki mellé, akit alig ismersz, és ismerd meg: kérdezz tőle legalább három dolgot, és jegyezd meg a nevét.", "AI – Lelki", 7, "Heti", "Koedukált", "Oldalra", "Alkalmazkodás", "Elvtelenség", "Lelki", "ai_user", true, "AI-NO-19"],
  ["Értékeim listája", "Írd le az öt legfontosabb értéket, amit a családodban képviselni szeretnél. Nézd meg, melyiket adtad fel az utóbbi hónapban mások kedvéért, és tegyél ma egy lépést, hogy visszaállítsd.", "AI – Szellemi", 1, "Napi", "Női", "Oldalra", "Alkalmazkodás", "Elvtelenség", "Szellemi", "ai_user", true, "AI-NO-20"],
  ["Kegyelmes lista", "Írd le a „jó anya, jó feleség” szabályaidat, amelyeket elvársz magadtól. Húzd át azokat, amelyeket nem Isten, hanem a maximalizmusod vagy mások várnak el, és imádkozz a szabadságért.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Engedelmesség", "Vak engedelmesség vagy legalizmus", "Lelki", "ai_user", true, "AI-NF-01"],
  ["Még aznap", "Öt napon át, amikor a lelkiismereted egy jó dologra indít (felhívni valakit, bocsánatot kérni, adni), tedd meg még aznap, halogatás nélkül.", "AI – Lelki", 5, "Heti", "Női", "Felfelé", "Engedelmesség", "Vak engedelmesség vagy legalizmus", "Lelki", "ai_user", true, "AI-NF-02"],
  ["Első a csendes idő", "Egy héten át kezdd a napot 10 perc igeolvasással és imával, mielőtt megnyitnád a telefonodat, akkor is, ha ehhez szoptatás vagy reggeliztetés közben kell leülnöd.", "AI – Lelki", 7, "Heti", "Női", "Felfelé", "Engedelmesség", "Vak engedelmesség vagy legalizmus", "Lelki", "ai_user", true, "AI-NF-03"],
  ["Pénzügyi őszinteség", "Nézzétek át ma őszintén a házastársaddal a család havi kiadásait. Ne szépítsetek: nevezzétek meg, ami gond, imádkozzatok érte, és döntsetek el egy konkrét lépést.", "AI – Szellemi", 1, "Napi", "Koedukált", "Felfelé", "Hit", "Valóságtagadás", "Szellemi", "ai_user", true, "AI-NF-04"],
  ["Ígéret a félelem ellen", "Öt napon át keress egy-egy bibliai ígéretet egy konkrét félelmedre (a gyerekek egészsége, a jövő, az anyagiak). Írd ki, és mondd ki hangosan, amikor előjön a félelem.", "AI – Lelki", 5, "Heti", "Női", "Felfelé", "Hit", "Valóságtagadás", "Lelki", "ai_user", true, "AI-NF-05"],
  ["Halogatott vizsgálat", "Van olyan egészségügyi vizsgálat, amit magadnál halogatsz (nőgyógyász, fogorvos, vérvétel, szűrés), mert „most a gyerekek a fontosak”? Foglald le ma az időpontot.", "AI – Fizikai", 1, "Napi", "Női", "Felfelé", "Hit", "Valóságtagadás", "Fizikai", "ai_user", true, "AI-NF-06"],
  ["Imaséta babakocsival", "Öt napon át a napi sétád egy részét (babakocsival, gyerekkel vagy egyedül) fordítsd imára: imádkozz a szomszédokért, az óvodáért, az útba eső házakért és a családodért.", "AI – Fizikai", 5, "Heti", "Női", "Felfelé", "Imádság", "Passzív várakozás", "Fizikai", "ai_user", true, "AI-NF-07"],
  ["Esti áldás", "Ma este lefekvés előtt tedd a kezed minden gyermeked fejére, és mondj fölötte hangosan egy rövid áldást vagy igét. Ha nincs gyereked, áldd meg így a férjedet.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Imádság", "Passzív várakozás", "Lelki", "ai_user", true, "AI-NF-08"],
  ["Imapartner", "Keress egy anyukát vagy barátnőt, akivel a héten minden nap küldtök egymásnak egy imakérést és egy imát (akár hangüzenetben). A hét végén osszátok meg, mi változott.", "AI – Lelki", 7, "Heti", "Női", "Felfelé", "Imádság", "Passzív várakozás", "Lelki", "ai_user", true, "AI-NF-09"],
  ["Imádkozó mosogatás", "Egy rutinmunka (mosogatás, teregetés, főzés) alatt ma ne hallgass semmit, hanem imádkozz végig név szerint azokért, akik eszedbe jutnak.", "AI – Fizikai", 1, "Napi", "Női", "Felfelé", "Imádság", "Passzív várakozás", "Fizikai", "ai_user", true, "AI-NF-10"],
  ["Családi esti ima", "Egy héten át vezess minden este egy rövid, 3–5 perces családi imát a gyerekekkel: egy hála, egy kérés, egy áldás. Ha a férjed szívesen vezeti, támogasd ebben.", "AI – Lelki", 7, "Heti", "Női", "Felfelé", "Imádság", "Passzív várakozás", "Lelki", "ai_user", true, "AI-NF-11"],
  ["Összehasonlítás-stop", "Egy héten át figyeld meg, mikor hasonlítod magad más anyukákhoz vagy feleségekhez (közösségi média, játszótér, gyülekezet). Minden ilyen alkalommal adj hálát egy dologért a saját életedben.", "AI – Szellemi", 7, "Heti", "Női", "Felfelé", "Istenfélelem", "Emberektől vagy büntetéstől való félelem", "Szellemi", "ai_user", true, "AI-NF-12"],
  ["Nyitott ajtó", "Hívj meg valakit egy kávéra úgy, hogy előtte nem takarítasz ki különösebben. Gyakorold, hogy a nyitott ajtód fontosabb annál, mit gondolnak a lakásodról.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Istenfélelem", "Emberektől vagy büntetéstől való félelem", "Lelki", "ai_user", true, "AI-NF-13"],
  ["Posztolásmentes hét", "Öt napon át ne posztolj semmit a családodról és a gyerekeidről. Figyeld meg, mennyire hiányzik mások visszajelzése, és vidd ezt Isten elé.", "AI – Szellemi", 5, "Heti", "Női", "Felfelé", "Istenfélelem", "Emberektől vagy büntetéstől való félelem", "Szellemi", "ai_user", true, "AI-NF-14"],
  ["Bátor vélemény", "Egy beszélgetésben (anyukák között, a családban, a kiscsoportban) mondd el ma a véleményed akkor is, ha tudod, hogy a többség mást gondol, szeretettel és tisztelettel.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Istenfélelem", "Emberektől vagy büntetéstől való félelem", "Szellemi", "ai_user", true, "AI-NF-15"],
  ["Csak annyi: köszönöm", "Öt napon át, ha valaki megdicsér, ne hárítsd el („ugyan, semmiség”), hanem mondd egyszerűen: „Köszönöm.” Este írd fel, mit dicsértek.", "AI – Lelki", 5, "Heti", "Női", "Felfelé", "Alázat", "Önleértékelés", "Lelki", "ai_user", true, "AI-NF-16"],
  ["Isten szerint én", "Keress öt igeverset arról, mit mond rólad Isten (pl. Zsolt 139, Ef 2:10, Ézs 43:1), írd ki őket, és olvasd fel hangosan.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Alázat", "Önleértékelés", "Lelki", "ai_user", true, "AI-NF-17"],
  ["Levél magamnak", "Írj levelet magadnak úgy, ahogy a legjobb barátnődnek írnál, ha ő lenne a helyzetedben: ismerd el a küzdelmeit, és bátorítsd.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Alázat", "Önleértékelés", "Szellemi", "ai_user", true, "AI-NF-18"],
  ["Igent mondok a segítségre", "Egy héten át fogadj el minden felajánlott segítséget (főzés, gyerekvigyázás, bevásárlás) a „nem kell, megoldom” helyett. Ha senki nem ajánl, kérj te legalább kétszer.", "AI – Szellemi", 7, "Heti", "Női", "Felfelé", "Alázat", "Önleértékelés", "Szellemi", "ai_user", true, "AI-NF-19"],
  ["Pihenés bűntudat nélkül", "Szánj ma 30 percet valódi pihenésre (alvás, fürdő, olvasás, egyedül töltött séta), ne hasznos elfoglaltságra. Ne kérj érte bocsánatot, és ne magyarázkodj.", "AI – Fizikai", 1, "Napi", "Női", "Felfelé", "Alázat", "Önleértékelés", "Fizikai", "ai_user", true, "AI-NF-20"],
  ["Anyai identitás", "Írd le, milyen anyának szeretnéd, hogy a gyerekeid lássanak, amikor felnőnek. Utána vizsgáld meg őszintén, hol tartasz most ehhez képest, és válassz ki egy területet.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Jövőkép", "Nagyzolás", "Szellemi", "ai_user", true, "AI-NF-21"],
  ["Tíz év múlva", "Írd le, milyen nő, feleség és hívő szeretnél lenni 10 év múlva. Válaszd ki a legfontosabb különbséget a mostanihoz képest, és írd mellé az első lépést.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Jövőkép", "Nagyzolás", "Szellemi", "ai_user", true, "AI-NF-22"],
  ["Közös jövőkép", "Szánjatok a héten egy estét a házastársaddal arra, hogy leírjátok: milyen családot szeretnétek 5 év múlva (hit, kapcsolatok, otthon, anyagiak). Legyen reális, és válasszatok egy közös első lépést.", "AI – Szellemi", 7, "Heti", "Koedukált", "Felfelé", "Jövőkép", "Nagyzolás", "Szellemi", "ai_user", true, "AI-NF-23"],
  ["Nélkülem is megy", "Írd le, milyen feladatokat vállaltál a családban, a gyülekezetben és az óvodában vagy iskolában. Jelöld meg, melyikre hívott Isten, és melyiket csak azért csinálod, mert „nélkülem nem megy”. Egyről mondj le, vagy add át.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Elhívástudat", "Messiáskomplexus", "Lelki", "ai_user", true, "AI-NF-24"],
  ["Mire hívtál most?", "Egy héten át imádkozz naponta: „Uram, mire hívtál engem ebben az életszakaszban?” Írd le, ami eszedbe jut, és a hét végén beszéld meg egy érett nőtestvérrel.", "AI – Lelki", 7, "Heti", "Női", "Felfelé", "Elhívástudat", "Messiáskomplexus", "Lelki", "ai_user", true, "AI-NF-25"],
  ["Kapcsolódás nőtárssal", "Hívj el egy nőtársadat egy kávéra vagy sétára. Ne olyasvalakit, akivel amúgy is rendszeresen találkozol.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Reménység", "Ábrándozás", "Lelki", "ai_user", true, "AI-NF-26"],
  ["Ábrándból lépés", "Van egy vágyad, amiről csak ábrándozol (saját vállalkozás, új szolgálat, egy közös utazás)? Írd le a reális első lépést, beszéld meg a férjeddel, és még a héten tedd meg.", "AI – Szellemi", 7, "Heti", "Női", "Felfelé", "Reménység", "Ábrándozás", "Szellemi", "ai_user", true, "AI-NF-27"],
  ["Elég jó otthon", "Egy héten át esténként csak 15 percig rendezz, időzítővel, és utána hagyd abba akkor is, ha nem tökéletes. A felszabaduló időt töltsd a férjeddel vagy magaddal.", "AI – Fizikai", 7, "Heti", "Női", "Felfelé", "Céltudatosság", "Megszállottság", "Fizikai", "ai_user", true, "AI-NF-28"],
  ["Egy fő cél a hétre", "Hétfőn írd le a hét egyetlen legfontosabb célját (családi, lelki vagy saját). Minden nap tegyél érte legalább 15 percet, és ne vállalj mellé semmi újat.", "AI – Szellemi", 7, "Heti", "Női", "Felfelé", "Céltudatosság", "Megszállottság", "Szellemi", "ai_user", true, "AI-NF-29"],
  ["Családi küldetésmondat", "Fogalmazzátok meg a házastársaddal egy mondatban, mire hívta Isten a családotokat. Írjátok ki, és tegyétek ki jól látható helyre.", "AI – Szellemi", 1, "Napi", "Koedukált", "Felfelé", "Küldetéstudat", "Önigazolás", "Szellemi", "ai_user", true, "AI-NF-30"],
  ["Amit tisztelek benne", "Írj le öt konkrét dolgot, amit tisztelsz a férjedben, és még ma mondd el neki legalább kettőt, nem hízelgésként, hanem konkrét példával.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Bátorítás", "Hízelgés", "Lelki", "ai_user", true, "AI-NF-31"],
  ["Anyabátorítás", "Öt napon át küldj naponta egy bátorító üzenetet egy-egy anyukának, akiről tudod, hogy nehéz időszakban van. Írd meg neki konkrétan, mit csinál jól.", "AI – Lelki", 5, "Heti", "Női", "Felfelé", "Bátorítás", "Hízelgés", "Lelki", "ai_user", true, "AI-NF-32"],
  ["Jellemdicséret", "Ma minden gyerekedet dicsérd meg konkrétan a jelleméért, ne a külsejéért vagy a teljesítményéért. („Láttam, milyen türelmes voltál a húgoddal.”)", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Bátorítás", "Hízelgés", "Szellemi", "ai_user", true, "AI-NF-33"],
  ["Önállóság-hét", "Egy héten át bízz rá minden gyerekedre egy új, a korának megfelelő önálló feladatot (öltözés, terítés, pakolás). Ne csináld meg helyette akkor sem, ha lassabb és tökéletlenebb.", "AI – Fizikai", 7, "Heti", "Női", "Felfelé", "Szolgáló vezetés", "Atyáskodó kontroll", "Fizikai", "ai_user", true, "AI-NF-34"],
  ["Családi kerekasztal", "Tarts egy rövid családi megbeszélést: kérdezd meg a gyerekeket és a férjedet, mi volt jó a héten, mi volt nehéz, és miben segíthetnél nekik.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Szolgáló vezetés", "Atyáskodó kontroll", "Szellemi", "ai_user", true, "AI-NF-35"],
  ["Az ő terhe", "Kérdezd meg a férjedet, mi a legnehezebb most a munkájában vagy a hétköznapjaiban, és még ma tégy valamit, ami ezen könnyít.", "AI – Fizikai", 1, "Napi", "Női", "Felfelé", "Szolgáló vezetés", "Atyáskodó kontroll", "Fizikai", "ai_user", true, "AI-NF-36"],
  ["Mentoranya", "Keress egy fiatalabb anyukát vagy feleséget, és a héten szánj rá időt: hallgasd meg, mondd el, mi segített neked, és imádkozz vele.", "AI – Lelki", 7, "Heti", "Női", "Felfelé", "Szolgáló vezetés", "Atyáskodó kontroll", "Lelki", "ai_user", true, "AI-NF-37"],
  ["Bűntudatkeltés nélkül", "Öt napon át figyelj arra, hogy a kéréseidhez ne kapcsolj bűntudatkeltést („bezzeg én…”, „senki nem segít”), sóhajtást vagy könnyeket nyomásként. Kérj tisztán, és fogadd el a választ.", "AI – Szellemi", 5, "Heti", "Női", "Felfelé", "Inspirálás", "Érzelmi manipuláció", "Szellemi", "ai_user", true, "AI-NF-38"],
  ["Így segített Isten", "Mesélj ma a gyerekeidnek (vagy egy fiatalabbnak) egy igaz történetet az életedből, amikor Isten segített. Ne tanulsággal zárd, hanem kérdezd meg, ők mit gondolnak róla.", "AI – Lelki", 1, "Napi", "Női", "Felfelé", "Inspirálás", "Érzelmi manipuláció", "Lelki", "ai_user", true, "AI-NF-39"],
  ["Kérdés kioktatás helyett", "Három napon át, amikor kioktatnád a férjedet vagy a gyerekedet, tegyél fel helyette egy kérdést („Szerinted mi lenne a jó megoldás?”), és hallgasd végig a választ.", "AI – Szellemi", 3, "Heti", "Női", "Felfelé", "Tanítás", "Kioktatás", "Szellemi", "ai_user", true, "AI-NF-40"],
  ["Közös konyha", "Taníts meg ma a gyerekednek egy konyhai vagy háztartási mozdulatot (tojásfeltörés, teregetés, ágyazás). Mutasd meg, hagyd csinálni, és ne vedd ki a kezéből, ha elsőre nem sikerül.", "AI – Fizikai", 1, "Napi", "Női", "Felfelé", "Tanítás", "Kioktatás", "Fizikai", "ai_user", true, "AI-NF-41"],
  ["Delegálási lista", "Írd össze, mely otthoni feladatokat végezhetné más is (férj, nagyobb gyerek, segítő). Válassz ki kettőt, és még ma beszéld meg, ki veszi át őket, világos elvárással.", "AI – Szellemi", 1, "Napi", "Női", "Felfelé", "Felhatalmazás", "Felelősség áthárítása", "Szellemi", "ai_user", true, "AI-NF-42"],
  ["A saját részem", "Öt napon át, amikor valami rosszul sül el, ne a férjedet, a gyerekeket vagy a körülményeket hibáztasd először: nevezd meg a saját részedet, és ha kell, kérj bocsánatot.", "AI – Lelki", 5, "Heti", "Női", "Felfelé", "Felhatalmazás", "Felelősség áthárítása", "Lelki", "ai_user", true, "AI-NF-43"]
];

function noiKihivasokBeirasa() {
  const sh = SpreadsheetApp.getActiveSpreadsheet().getSheets().find((s) => s.getSheetId() === TARGET_GID);
  if (!sh) throw new Error('Nem találom a kihíváskatalógus fület (gid ' + TARGET_GID + ').');

  const header = sh.getRange(HEADER_ROW, 1, 1, HEADERS.length).getDisplayValues()[0].map((h) => h.trim());
  HEADERS.forEach((h, i) => {
    if (header[i] !== h) throw new Error('Váratlan fejléc a(z) ' + (i + 1) + '. oszlopban: "' + header[i] + '" (várt: "' + h + '")');
  });

  const firstData = HEADER_ROW + 1;
  const n = Math.max(sh.getLastRow() - HEADER_ROW, 1);
  const titles = sh.getRange(firstData, 1, n, 1).getDisplayValues();
  const sources = new Set(sh.getRange(firstData, 13, n, 1).getDisplayValues().map((r) => r[0].trim()));

  let lastFilled = HEADER_ROW;
  titles.forEach((r, i) => { if (r[0].trim()) lastFilled = firstData + i; });

  const rows = ROWS.filter((r) => !sources.has(r[12]));
  if (!rows.length) return report('Mind a ' + ROWS.length + ' sor már bent van, nem írtam be semmit.');

  const start = lastFilled + 1;
  const end = start + rows.length - 1;
  if (end > sh.getMaxRows()) sh.insertRowsAfter(sh.getMaxRows(), end - sh.getMaxRows());

  sh.getRange(start, 12, rows.length, 1).insertCheckboxes();
  sh.getRange(start, 1, rows.length, HEADERS.length).setValues(rows);

  // Az "Érvényes?" oszlop soronkénti képletét (ha van) továbbmásolja az új sorokra.
  const formula = sh.getRange(firstData, 14).getFormulaR1C1();
  if (formula) sh.getRange(start, 14, rows.length, 1).setFormulaR1C1(formula);

  report(rows.length + ' új sor beírva: ' + start + '–' + end + '. sor.');
}

function report(msg) {
  Logger.log(msg);
  try { SpreadsheetApp.getUi().alert(msg); } catch (e) { /* futtatás szerkesztőből, UI nélkül */ }
}
